# Specify the version of Docker Compose file format
version: '3.8'

services:
  # Backend service configuration
  backend:
    # Build the Docker image for the backend service
    build:
      # Specify the build context directory containing the Dockerfile
      context: ./backend
      # Point to the Dockerfile used for building the image
      dockerfile: Dockerfile
    # Map port 8000 on the host to port 8000 in the container
    ports:
      - "8000:8000"

  # Frontend service configuration
  frontend:
    # Build the Docker image for the frontend service
    build:
      # Specify the build context directory containing the Dockerfile
      context: ./my-frontend
      # Point to the Dockerfile used for building the image
      dockerfile: Dockerfile
    # Map port 8085 on the host to port 80 in the container
    ports:
      - "3000:80"
    # Declare that the frontend service depends on the backend service
    depends_on:
      - backend