# Use an official Node.js image as the base image
FROM node:16 as build

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Build the React app
RUN npm run build

# Use an Nginx image to serve the static files
FROM nginx:alpine

# Copy the generated build folder from the first stage to the Nginx web server
COPY --from=build /app/build /usr/share/nginx/html

# Expose port 80 to allow communication with the container
EXPOSE 80

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]